### ISSUE TITLE
Is it possible to: Filter depending on the local time? Setting shipping rates by API?

### ISSUE THREAD

**Issue by joanlopez** [christianblais/parcelify#6]
Hi @christianblais,

We're trying to integrate our local pick-up shipment provider. For this integration, we need some things:

- Create a shipping option that corresponds to this provider.
- Filter this shipping option by the zip codes where they provide shipment services.
- Filter this shipping option by local time, for example, only showing this option between 8am to 5pm.

I've achieved the first two points. The second one with your Parcelify app, I have to thank you for this.
Now I have some questions about how to achieve the third one:

- Is it possible to filter shipping rates by hours? I can contribute you in development tasks if needed.
- Is it possible to manage it (create & edit Parcelify shipping rates) by API?

I guess the first option is quite complex to get and check the local times, etc. However, I think a good way could be doing this task from our servers. This way, I can create a cronjob that each day enable the shipping method at 8am, and another one to disable it at 5pm. The main problem for this second approach is that it would mean that there should be available any way to enable/disable shipping rates through an HTTP request or something similar to the Shopify API.

Again, I can contribute with development tasks if needed.

Any comment from your POV will be very appreciated.

Thanks a lot @christianblais!

**Comment by christianblais** [comment]
Unfortunately, adding time wouldn't work quite well with the current regex pattern. As for disabling/enabling rates through the API, I'd be reluctant to add that because I'm running on some rather small Heroku servers, and that would open me up the the outside world. Scary.

Does it really make sense to prevent people from picking that rate during outside hours? What if at 6h, I'm willing to wait until tomorrow morning? Are you sure what you want isn't rather inform customers of your opening hours? You could potentially use the description for that, and add "Opened from 8am to 5pm, every week-day" that everyone could see at checkout. Could that be a solution?

Otherwise, the app is open sourced, so you can always fork and tweak to your needs if required.

**Comment by joanlopez** [comment]
Thanks a lot @christianblais,
Adding the comment you mentioned in the description is one of the options that we're evaluating.
Everything is clear, so I proceed to close this issue.
Again, thanks!
